name: toodoo
description: Let us do our TooDoos quickly
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  sqflite: ^1.3.2+1
  swipedetector: 1.2.0
  toast: ^0.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true

  # assets:
  #   - images/a_dot_burr.jpeg

  fonts:
    - family: SFPro
      fonts:
        - asset: assets/fonts/SFPro.ttf